/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import util.GerenteDeTelas;

/**
 *
 * @author vitor
 */
public class Home extends javax.swing.JFrame {

    GerenteDeTelas gerenteDeTelas;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.gerenteDeTelas = new GerenteDeTelas(homePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        homePanel = new javax.swing.JDesktopPane();
        livros = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emprestimos = new javax.swing.JLabel();
        leitores = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca do Castor");
        setExtendedState(6);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(230, 235, 238));

        livros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/iconEstante.png"))); // NOI18N
        livros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                livrosMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 3, 36)); // NOI18N
        jLabel4.setText("Home");

        emprestimos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/logoCastor .png"))); // NOI18N
        emprestimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emprestimosMouseClicked(evt);
            }
        });

        leitores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/iconCadastro.png"))); // NOI18N
        leitores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leitoresMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cambria Math", 2, 24)); // NOI18N
        jLabel8.setText("Leitores");

        jLabel9.setFont(new java.awt.Font("Cambria Math", 2, 24)); // NOI18N
        jLabel9.setText("Emprestimos");

        jLabel5.setFont(new java.awt.Font("Cambria Math", 2, 24)); // NOI18N
        jLabel5.setText("Livros");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        homePanel.setLayer(livros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homePanel.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homePanel.setLayer(emprestimos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homePanel.setLayer(leitores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homePanel.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homePanel.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homePanel.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        homePanel.setLayer(logout, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(livros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                        .addComponent(emprestimos)))
                .addGap(236, 236, 236)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leitores)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)))
                .addGap(117, 117, 117))
        );

        homePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {emprestimos, jLabel4, leitores, livros});

        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(livros)
                            .addComponent(emprestimos))
                        .addGap(18, 18, 18)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout)
                        .addContainerGap())
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(leitores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(327, 327, 327))))
        );

        homePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {emprestimos, jLabel4, leitores, livros});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void leitoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leitoresMouseClicked
        gerenteDeTelas.abrirTelas(Leitor.getInstancia());
        /*Leitor leitor = new Leitor();
        homePanel.add(leitor);
        leitor.setVisible(true);*/
    }//GEN-LAST:event_leitoresMouseClicked

    private void emprestimosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emprestimosMouseClicked
        gerenteDeTelas.abrirTelas(Emprestimo.getInstancia());
        /*Emprestimo emprestimo = new Emprestimo();
        homePanel.add(emprestimo);
        emprestimo.setVisible(true);*/
    }//GEN-LAST:event_emprestimosMouseClicked

    private void livrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livrosMouseClicked
        gerenteDeTelas.abrirTelas(Livro.getInstancia());
        /*Livro livro = new Livro();
        homePanel.add(livro);
        livro.setVisible(true);*/
    }//GEN-LAST:event_livrosMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emprestimos;
    private javax.swing.JDesktopPane homePanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel leitores;
    private javax.swing.JLabel livros;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
